name: CI
permissions:
  contents: read
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pyyaml

    - name: Run YAML tests
      run: |
        python tests/test_yaml_frameworks.py
    
    - name: Run bug fix tests
      run: |
        python tests/test_bug_fixes.py
        name: CI
